version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/self.yml

env:
  global:
    - REQUIRE_RECIPE_TESTING="^2"
    - REQUIRE_FRAMEWORKTEST="^0.4.2"
    # vfsstream is a dev dependency of the assets module
    - REQUIRE_EXTRA="mikey179/vfsstream:^1.6.10"

matrix:
  fast_finish: true
  include:
    # Core php tests
    - php: 7.4
      env:
        - DB=MYSQL
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="core"
        - PDO=1
        - COMPOSER_INSTALL_ARG="--prefer-lowest"
    - php: 7.4
      env:
        - DB=MYSQL
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="framework"
    - php: 7.4
      env:
        - DB=MYSQL
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="core"
    - php: 8.0
      env:
        - DB=MYSQL
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="core"
    - php: 8.1.0
      env:
        - DB=MYSQL
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="core"
    # admin php tests
    - php: 7.4
      env:
        - DB=MYSQL
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="admin"
        - PDO=1
        - COMPOSER_INSTALL_ARG="--prefer-lowest"
    - php: 7.4
      env:
        - DB=MYSQL
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="admin"
    - php: 8.0
      env:
        - DB=MYSQL
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="admin"
    - php: 8.1.0
      env:
        - DB=MYSQL
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="admin"
    # behat tests
    - php: 7.4
      env:
        - DB=MYSQL
        - BEHAT_TEST=1
        - BEHAT_SUITE="admin"
    - php: 7.4
      env:
        - DB=MYSQL
        - BEHAT_TEST=1
        - BEHAT_SUITE="cms"
    - php: 7.4
      env:
        - DB=MYSQL
        - BEHAT_TEST=1
        - BEHAT_SUITE="asset-admin"
